
@host = http://localhost:3000

GET {{host}}/cart
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QgY2FydDMiLCJlbWFpbCI6InRlc3RDYXJ0M0BnbWFpbC5jb20iLCJzdWIiOiI2M2MyMjIzZmY5ZDcxODA5MjE1YTQ4YTIiLCJyb2xlcyI6WyJ1c2VyIl0sImlhdCI6MTY3MzY2NzE0MywiZXhwIjoxNzA0NzcxMTQzfQ.sMK6t7lNIXVWtUNJ7-o4G9Nkbe5aFVN6CSelYuVntRA

