
@host = http://localhost:3000

GET {{host}}/location/63af073706a7d5b3069c8d08
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkZWwiLCJlbWFpbCI6ImEuYWRlbEBtYWlsLmNvbSIsInN1YiI6IjYzOWVmMTY0NDJiNTVhOTU4N2NmZjI0MSIsInJvbGVzIjpbImFkbWluIl0sImlhdCI6MTY3MzAxOTk4MiwiZXhwIjoxNzA0MTIzOTgyfQ.2iCJowkyGd3ZVkEuJKvheFCnt0B-33hpcgnKcRTRotw


